---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/aacsjour/repositories/aacs 
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH && pip install -r requirements.txt --user
