---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/aacsjour/dev.aacsjournals.com
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R backend/* $DEPLOYPATH/
    - /bin/cp -R backend/.htaccess $DEPLOYPATH/
    - cd $DEPLOYPATH && /home2/aacsjour/virtualenv/dev/3.11/bin/pip install -r requirements.txt
